# Generated by Django 3.0.1 on 2019-12-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('city', models.CharField(max_length=60, verbose_name='城市')),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name': '出版商',
                'verbose_name_plural': '出版商',
            },
        ),
    ]
