# Generated by Django 3.0.1 on 2019-12-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='aa',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
